package com.ansuru.ams.svr.user.entity;

public class Asset {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.id
     *
     * @mbggenerated Tue Sep 10 21:39:31 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.asset_code
     *
     * @mbggenerated Tue Sep 10 21:39:31 CST 2019
     */
    private String assetCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.asset_name
     *
     * @mbggenerated Tue Sep 10 21:39:31 CST 2019
     */
    private String assetName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.id
     *
     * @return the value of asset.id
     *
     * @mbggenerated Tue Sep 10 21:39:31 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.id
     *
     * @param id the value for asset.id
     *
     * @mbggenerated Tue Sep 10 21:39:31 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.asset_code
     *
     * @return the value of asset.asset_code
     *
     * @mbggenerated Tue Sep 10 21:39:31 CST 2019
     */
    public String getAssetCode() {
        return assetCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.asset_code
     *
     * @param assetCode the value for asset.asset_code
     *
     * @mbggenerated Tue Sep 10 21:39:31 CST 2019
     */
    public void setAssetCode(String assetCode) {
        this.assetCode = assetCode == null ? null : assetCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.asset_name
     *
     * @return the value of asset.asset_name
     *
     * @mbggenerated Tue Sep 10 21:39:31 CST 2019
     */
    public String getAssetName() {
        return assetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.asset_name
     *
     * @param assetName the value for asset.asset_name
     *
     * @mbggenerated Tue Sep 10 21:39:31 CST 2019
     */
    public void setAssetName(String assetName) {
        this.assetName = assetName == null ? null : assetName.trim();
    }
}