package com.ansuru.ams.svr.user.entity;

import java.util.Date;

public class Asset {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.id
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.asset_code
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    private String assetCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.asset_name
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    private String assetName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.asset_cate
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    private Short assetCate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.used_status
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    private Short usedStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.lent_user
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    private String lentUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.lent_start_dt
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    private Date lentStartDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.lent_end_dt
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    private Date lentEndDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.note
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.delete_flag
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    private String deleteFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.created_dt
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    private Date createdDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.created_name
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    private String createdName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.modified_dt
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    private Date modifiedDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.modified_name
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    private String modifiedName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.id
     *
     * @return the value of asset.id
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.id
     *
     * @param id the value for asset.id
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.asset_code
     *
     * @return the value of asset.asset_code
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    public String getAssetCode() {
        return assetCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.asset_code
     *
     * @param assetCode the value for asset.asset_code
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    public void setAssetCode(String assetCode) {
        this.assetCode = assetCode == null ? null : assetCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.asset_name
     *
     * @return the value of asset.asset_name
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    public String getAssetName() {
        return assetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.asset_name
     *
     * @param assetName the value for asset.asset_name
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    public void setAssetName(String assetName) {
        this.assetName = assetName == null ? null : assetName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.asset_cate
     *
     * @return the value of asset.asset_cate
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    public Short getAssetCate() {
        return assetCate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.asset_cate
     *
     * @param assetCate the value for asset.asset_cate
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    public void setAssetCate(Short assetCate) {
        this.assetCate = assetCate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.used_status
     *
     * @return the value of asset.used_status
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    public Short getUsedStatus() {
        return usedStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.used_status
     *
     * @param usedStatus the value for asset.used_status
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    public void setUsedStatus(Short usedStatus) {
        this.usedStatus = usedStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.lent_user
     *
     * @return the value of asset.lent_user
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    public String getLentUser() {
        return lentUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.lent_user
     *
     * @param lentUser the value for asset.lent_user
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    public void setLentUser(String lentUser) {
        this.lentUser = lentUser == null ? null : lentUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.lent_start_dt
     *
     * @return the value of asset.lent_start_dt
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    public Date getLentStartDt() {
        return lentStartDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.lent_start_dt
     *
     * @param lentStartDt the value for asset.lent_start_dt
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    public void setLentStartDt(Date lentStartDt) {
        this.lentStartDt = lentStartDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.lent_end_dt
     *
     * @return the value of asset.lent_end_dt
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    public Date getLentEndDt() {
        return lentEndDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.lent_end_dt
     *
     * @param lentEndDt the value for asset.lent_end_dt
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    public void setLentEndDt(Date lentEndDt) {
        this.lentEndDt = lentEndDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.note
     *
     * @return the value of asset.note
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.note
     *
     * @param note the value for asset.note
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.delete_flag
     *
     * @return the value of asset.delete_flag
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    public String getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.delete_flag
     *
     * @param deleteFlag the value for asset.delete_flag
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag == null ? null : deleteFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.created_dt
     *
     * @return the value of asset.created_dt
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    public Date getCreatedDt() {
        return createdDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.created_dt
     *
     * @param createdDt the value for asset.created_dt
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    public void setCreatedDt(Date createdDt) {
        this.createdDt = createdDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.created_name
     *
     * @return the value of asset.created_name
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    public String getCreatedName() {
        return createdName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.created_name
     *
     * @param createdName the value for asset.created_name
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    public void setCreatedName(String createdName) {
        this.createdName = createdName == null ? null : createdName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.modified_dt
     *
     * @return the value of asset.modified_dt
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    public Date getModifiedDt() {
        return modifiedDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.modified_dt
     *
     * @param modifiedDt the value for asset.modified_dt
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    public void setModifiedDt(Date modifiedDt) {
        this.modifiedDt = modifiedDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.modified_name
     *
     * @return the value of asset.modified_name
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    public String getModifiedName() {
        return modifiedName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.modified_name
     *
     * @param modifiedName the value for asset.modified_name
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    public void setModifiedName(String modifiedName) {
        this.modifiedName = modifiedName == null ? null : modifiedName.trim();
    }
}