package com.ansuru.ams.svr.user.entity;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.nickname
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.realname
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    private String realname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.hired_dt
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    private Date hiredDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.fired_dt
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    private Date firedDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.avatar
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    private String avatar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.note
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.delete_flag
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    private String deleteFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.created_dt
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    private Date createdDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.created_name
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    private String createdName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.modified_dt
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    private Date modifiedDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.modified_name
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    private String modifiedName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.nickname
     *
     * @return the value of user.nickname
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.nickname
     *
     * @param nickname the value for user.nickname
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.realname
     *
     * @return the value of user.realname
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.realname
     *
     * @param realname the value for user.realname
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.hired_dt
     *
     * @return the value of user.hired_dt
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    public Date getHiredDt() {
        return hiredDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.hired_dt
     *
     * @param hiredDt the value for user.hired_dt
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    public void setHiredDt(Date hiredDt) {
        this.hiredDt = hiredDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.fired_dt
     *
     * @return the value of user.fired_dt
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    public Date getFiredDt() {
        return firedDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.fired_dt
     *
     * @param firedDt the value for user.fired_dt
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    public void setFiredDt(Date firedDt) {
        this.firedDt = firedDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.avatar
     *
     * @return the value of user.avatar
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.avatar
     *
     * @param avatar the value for user.avatar
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.note
     *
     * @return the value of user.note
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.note
     *
     * @param note the value for user.note
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.delete_flag
     *
     * @return the value of user.delete_flag
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    public String getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.delete_flag
     *
     * @param deleteFlag the value for user.delete_flag
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag == null ? null : deleteFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.created_dt
     *
     * @return the value of user.created_dt
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    public Date getCreatedDt() {
        return createdDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.created_dt
     *
     * @param createdDt the value for user.created_dt
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    public void setCreatedDt(Date createdDt) {
        this.createdDt = createdDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.created_name
     *
     * @return the value of user.created_name
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    public String getCreatedName() {
        return createdName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.created_name
     *
     * @param createdName the value for user.created_name
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    public void setCreatedName(String createdName) {
        this.createdName = createdName == null ? null : createdName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.modified_dt
     *
     * @return the value of user.modified_dt
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    public Date getModifiedDt() {
        return modifiedDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.modified_dt
     *
     * @param modifiedDt the value for user.modified_dt
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    public void setModifiedDt(Date modifiedDt) {
        this.modifiedDt = modifiedDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.modified_name
     *
     * @return the value of user.modified_name
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    public String getModifiedName() {
        return modifiedName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.modified_name
     *
     * @param modifiedName the value for user.modified_name
     *
     * @mbggenerated Fri Sep 13 16:14:47 CST 2019
     */
    public void setModifiedName(String modifiedName) {
        this.modifiedName = modifiedName == null ? null : modifiedName.trim();
    }
}